apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-elasticsearch-dpi
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-dpi
spec:
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: sc-elasticsearch-dpi
  local:
    path: /data/dpi/elasticsearch/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mwsacc3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elasticsearch-dpi
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-elasticsearch-dpi
  resources:
    requests:
      storage: 25Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    application: elasticsearch
    type: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values: ["mwsacc3"]
      containers:
      - name: elasticsearch
        image: dpi/elasticsearch:7.6.2
        env:
          - name: discovery.type
            value: single-node
        volumeMounts:
        - name: vol-mnt-elasticsearch-dpi
          mountPath: /usr/share/elasticsearch/data
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: nodes
      volumes:
        - name: vol-mnt-elasticsearch-dpi
          persistentVolumeClaim:
           claimName: pvc-elasticsearch-dpi

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: logging
  labels:
    application: elasticsearch
    type: external
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: nodes
  selector:
    app: elasticsearch

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-external-service
  namespace: ns-dpi
spec:
  type: ExternalName
  externalName: elasticsearch-service.logging.svc.cluster.local
  ports:
   - name: http
     port: 9200
   - name: node
     port: 9300

---
