apiVersion: v1 
kind: Namespace 
metadata:
  name: ns-dpi 

--- 
apiVersion: v1 
kind: Namespace 
metadata:
  name: kafka

---

apiVersion: v1
kind: Namespace
metadata:
  name: logging

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
